FROM richarvey/nginx-php-fpm:3.1.6

COPY . .

# Image config
ENV SKIP_COMPOSER 1
ENV WEBROOT /var/www/html/public
ENV PHP_ERRORS_STDERR 1
ENV RUN_SCRIPTS 1
ENV REAL_IP_HEADER 1

# Laravel config
ENV APP_ENV locale
ENV APP_DEBUG true
ENV APP_NAME Habitly
ENV APP_URL https://habit-tracker-fddo.onrender.com/
ENV DB_CONNECTION mysql
ENV DB_HOST 127.0.0.1
ENV DB_PORT 3306
ENV DB_DATABASE habittraker
ENV DB_USERNAME root
ENV DB_PASSWORD s
ENV BROADCAST_CONNECTION log
ENV MAIL_MAILER smtp
ENV MAIL_HOST smtp.gmail.com
ENV MAIL_PORT 587
ENV MAIL_USERNAME s
ENV MAIL_PASSWORD s
ENV MAIL_ENCRYPTION tls
ENV MAIL_FROM_ADDRESS "a"
ENV MAIL_FROM_NAME "${APP_NAME}"
ENV JWT_SECRET s
ENV QUEUE_CONNECTION database
# Allow composer to run as root
ENV COMPOSER_ALLOW_SUPERUSER 1

CMD ["/start.sh"]
